### ISSUE TITLE
javascript-based terminal-like interaction in the web version?

### ISSUE THREAD

**Issue by elad661** [elad661/curlbus#1]
It would be cool if there was a blinking cursor on the bottom of each HTML page generated by curlbus, that would accept simple commands to interact with the app (so people won't have to go to the URL bar all the time).

**Comment by elad661** [comment]
Possibilities: 
* unix like path commands like `cd`, `pwd`, and `ls`?
* just the name of the endpoint, no "command", for example `dan` if in `/operators` would go to `/operators/dan`?

**Comment by zeari** [comment]
Solved by https://github.com/elad661/curlbus/pull/9
