### ISSUE TITLE
Some stations do not have a full address, only a street name

### ISSUE THREAD

**Issue by guysoft** [elad661/curlbus#20]
Not sure if its a parsing issue so reporting.
I am trying to group stations that are close to each other, I found that he best way so far was to group them according to street address (street name + number). 
The reason is that it lets you also figure out which direction the bus is going. 

However, it seems that not all addresses have a number, for example

station id: ``21472``

Address field:
```
{'name': {'HE': 'קניון עזריאלי/דרך בגין', 'EN': 'Azrieli Mall/Begin Road', 'AR': 'كنيون عزريئيلي/ديريخ بيجين'}, 'address': {'street': 'דרך מנחם בגין', 'city': 'Tel Aviv Yafo', 'platform': '', 'floor': ''}, 'location': {'lat': 32.074914, 'lon': 34.790734}}
```
Note ``address': {'street': 'דרך מנחם בגין',``
And they did not give a number.

Its sister station is (one going the other way):

Station id: ``21669``
```
{'name': {'HE': 'קניון עזריאלי/דרך בגין', 'EN': 'Azrieli Mall/Begin Road', 'AR': 'كنيون عزريئيلي/ديريخ بيجين'}, 'address': {'street': 'דרך מנחם בגין', 'city': 'Tel Aviv Yafo', 'platform': '', 'floor': ''}, 'location': {'lat': 32.07569, 'lon': 34.791667}}
```

Just making sure you didn't miss some data from the original call.
Also any suggestions how to group stations would be helpful.
Using GPS would not help because it could catch stations from either side of the road.

**Comment by elad661** [comment]
The dataset does not have an address for this station. Some stations don't have addresses. 

It's best to just group stations by name, and people will understand the direction by the direction of the buses going through. This is how any other transit app does it. You can also show a map with the exact location of the stop if you have enough space on your screen.

Most transit users I know don't know or care about addresses of the stops, but rather the name (which is written on the stop sign) or the stop code (if they're geeks).

**Comment by guysoft** [comment]
I found several stations that have identical street addresses, but different names. Usually when the operator is not the same. That is what made me use street addresses in the first place.
