### ISSUE TITLE
special-casing for Israel Railways

### ISSUE THREAD

**Issue by elad661** [elad661/curlbus#3]
Israel Railways lines only have `long_name`, and no `short_name`, so there aren't really any meaningful numbers to be used for filtering on `/rail/{route_number}`

I need to come up with a system to assign numbers/short English names to the rail route numbers, and to have an index of them in `/rail` or `/rail/routes`.

**Comment by elad661** [comment]
Israel Railways has 68 route variations - including partial versions of some lines off-peak, temporary services during station closures, etc. A passenger doesn't are about these variation, and only cares about the ~13 "official" lines that are represented on Israel Railways map.

Questions:
* What is the usecase? Do people care about getting a route map with ETAs to all stations, or only want it as a way to find a stop code?
* If we do want to show a route map, what would we show for an ETA? if someone wants a train from Savidor to Haifa they don't care where it came from or where the final destination is, only when is the next relevant train.
* Would `/rail/<origin_code>/<destination_code>` to show a map/table for all trains from `origin` to `destination` work? Or even generalizing it to `/<origin_code>/to/<destination_code>`? 
  * I don't want to implement complex path finding (transfers, etc), so that would be direct ones only
  * Would this be actually useful with real-time data only? Otherwise a lot more code would need to be written to handle GTFS schedule dates & times, and I avoided that in curlbus so far
* Does a `/rail/stations` endpoint make sense to show all Israel Railways stations and their stop_code?


cc: @yuvadm what do you think?

**Comment by yuvadm** [comment]
Agree that train route don't really make sense. I guess the best and easiest use case would probably be to just show me which trains are arriving at a specific station. So something like `/rail/stations` sounds reasonable if it's easy to implement.

**Comment by elad661** [comment]
Added `/rail/stations` as an easy shortcut to get station codes. Please try it and let me know if you have any feedback :)

I might implement some of the other ideas in my previous comment later (and maybe even fuzzy station search by name, not sure).

**Comment by yuvadm** [comment]
Works great! Lots of inconsistencies in the station names though, but that's probably not your fault.

**Comment by elad661** [comment]
I didn't write them myself, I'm using the MoT dataset directly. It's full of spelling inconsistencies and mistakes,.

For example, they think "Nat-bg" is a name that make sense, they sometimes have " as an acronym separator in English, they spell Modi'in in at least 5 different ways, and sometimes have `''` in the source strings and `"` in the translations table or vise versa, causing lookups to fail (I have a quirk for this in curlbus).

One of the most glaring errors I've noticed in the past is that they translated "חיים לבנון" to "Life Lebanon".

Since the dataset is so large and the errors are basically everywhere, it's probably not worth the time&effort to correct these issues.

**Comment by yuvadm** [comment]
:woman_facepalming:
